### ISSUE TITLE
clover doesn't load when the last booted os is steamos 

### ISSUE THREAD

**Issue by arvz** [ryanrudolfoba/SteamDeck-Clover-dualboot#59] opened 2024-04-14 13:48 UTC
installed clover on my steam deck oled. I chose steamos as the default option. 

after restarting the first time, clover appears, everything works great. 

I load into steam os, restart again, this time there's no clover, just goes straight to steamos. 
even after shutting down, it always boots into steamos 

if I choose clover from the boot menu, I can get clover back. 
now if I boot into windows after this, then when I restart or shut down, clover loads correctly. 

seems to not work only when the last booted os is steamos? 

also tried changing the default os to windows. still boots to steamos when the last os was steamos
also tried re-running the script again, and same thing happens, first restart is good, then doesn't work anymore

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/3252230/eedc68c7-562f-49d8-9bea-1d3a3dbe02c0)

the boot order in efibootmgr seems correct also:

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/3252230/54824f3b-3f44-426f-9248-564ba5492365)

**Comment by ryanrudolfoba** [comment] 2024-04-14 20:52
Your second screenshot - the one that says BootNext 001. That is the culprit - it means on next reboot it will boot 001 which is assigned to SteamOS.

Do you have other scripts installed that could be interfering with the clover script?

Edit:

Try this to troubleshoot -

Uninstall Clover, reboot manually to SteamOS then run the efibootmgr command again. Take note if there is a BootNext item.

**Comment by arvz** [comment] 2024-04-15 14:28
I've uninstalled clover, shut down, booted to steamos using the boot menu, run efibootmgr again:

![image](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/3252230/ba7ed3b6-0473-4313-8966-3f0c2ab9d57e)

the BootNext: 0001 is still there. 

a while ago I did run a command that is supposed to make steamos the default os instead of windows - maybe that's why this is happening? I can't remember what the command was though. any suggestions?

**Comment by arvz** [comment] 2024-04-15 14:54
I tried `sudo efibootmgr --delete-bootnext` which seems to remove the BootNext. after running the script again, the BootNext comes back, but it is pointing to 0004 which is clover. restarted, and it boots to clover, but then I restart again, and we're back to the original problem, BootNext: 0001 (steamos)

**Comment by ryanrudolfoba** [comment] 2024-04-15 15:17
Definitely there is a startup script that is causing that BootNext item to appear. If you have a link of the guide you followed prior to clover we can take a look at it and figure out how to remove it.

**Comment by arvz** [comment] 2024-04-16 03:20
ok I found it, it was from this comment: https://www.reddit.com/r/WindowsOnDeck/comments/100puqr/comment/k1l9ti1/ 
it's just setting the `BootOrder` though, not a startup script. before I ran this command my steam deck would always default to restarting to Windows no matter which OS was the last one booted, so I don't think there's any startup script other than clover

**Comment by ryanrudolfoba** [comment] 2024-04-29 18:43
closing this issue as it is not related to the clover script. issue is caused by 3rd party script / tools messing with the BootNext parameter.

**Closed by ryanrudolfoba** 2024-04-29 18:43 UTC
